base_id: appFPoOfBpUv73M5A
base_name: AI Development Platform
table_id: tblSy63NxSHVSEOCo
table_name: AgentVersions
exported_at: '2025-12-28T14:12:03.624340'
field_count: 21
fields:
- id: fldRm0xc6quWcgi2c
  name: AgentVersionName
  type: singleLineText
  description: null
- id: fldqzFJc7FTPDmQlw
  name: Agent
  type: multipleRecordLinks
  description: null
  linked_table_id: tblVEJD2inVhae855
  prefer_single_record_link: true
  inverse_link_field_id: fldTtH9VwmFNHTLv1
- id: fldwmdrhop7QPXsGA
  name: BeamGraphID
  type: singleLineText
  description: null
- id: fld58k012qb1XiugP
  name: AgentVersion AID
  type: formula
  description: null
  referenced_field_ids: []
  formula: RECORD_ID()
- id: fldt8fSMQRhrJM9Rf
  name: Version Number
  type: number
  description: null
  precision: 0
- id: fldFsXt3lTx1wu4yf
  name: Node Versions
  type: multipleRecordLinks
  description: null
  linked_table_id: tblh0GsN5Et3ApzLS
  prefer_single_record_link: false
  inverse_link_field_id: fldpsyKaousktKsO3
- id: fldEGigMotSRfDZ1s
  name: Created At
  type: dateTime
  description: null
  date_format:
    name: local
    format: l
  time_format:
    name: 24hour
    format: HH:mm
  time_zone: client
- id: fldW9b8TmWQTWFshq
  name: Updated At
  type: dateTime
  description: null
  date_format:
    name: local
    format: l
  time_format:
    name: 24hour
    format: HH:mm
  time_zone: client
- id: fldfcNEomnDsgaDcZ
  name: Created By
  type: multipleRecordLinks
  description: null
  linked_table_id: tbl6mvvqpU4AOIpVS
  prefer_single_record_link: true
  inverse_link_field_id: fldga20CDF6SS6wTC
- id: fldC2xLvzzAwBtqgG
  name: DatasetRuns
  type: singleLineText
  description: null
- id: fldLLJeaX8gBAP7b6
  name: Version Evolution
  type: aiText
  description: null
  referenced_field_ids:
  - fldt8fSMQRhrJM9Rf
  - fldRm0xc6quWcgi2c
  - fldEGigMotSRfDZ1s
  - fldfcNEomnDsgaDcZ
- id: fld9TlCbOspIO34fr
  name: Tasks
  type: multipleRecordLinks
  description: null
  linked_table_id: tblsEzGhn4XJjNrkt
  prefer_single_record_link: false
  inverse_link_field_id: fldWSl6TIcA70RjQa
- id: fldsr0zl7qoqP1oT3
  name: Agents
  type: multipleRecordLinks
  description: null
  linked_table_id: tblVEJD2inVhae855
  prefer_single_record_link: false
  inverse_link_field_id: fld1DfIMFWJToupEr
- id: fldgydCqAcxM06Mlv
  name: Datasets
  type: multipleRecordLinks
  description: null
  linked_table_id: tbltUrvSBnfOb4S8v
  prefer_single_record_link: false
  inverse_link_field_id: fldplribrFKOV5pch
- id: fldptv1tmn01Au1sl
  name: DatasetTasks
  type: multipleRecordLinks
  description: null
  linked_table_id: tbl9lACSI4fDUzAv4
  prefer_single_record_link: false
  inverse_link_field_id: fldOtkN7N7vSx9fVd
- id: fld4SblYxVaZNUcxK
  name: Avg Production Accuracy
  type: rollup
  description: null
  record_link_field_id: fldFsXt3lTx1wu4yf
  lookup_field_id: fldSyqc1mWHlsHj5a
  referenced_field_ids: []
- id: fldU7akXjIcBUKT1R
  name: Avg Evaluation Accuracy
  type: rollup
  description: null
  record_link_field_id: fldFsXt3lTx1wu4yf
  lookup_field_id: fldz69TGXPDBU8ME8
  referenced_field_ids: []
- id: flddD77o85a1dKwip
  name: DatasetRun
  type: multipleRecordLinks
  description: null
  linked_table_id: tblOrJsp3sqWPGmD6
  prefer_single_record_link: false
  inverse_link_field_id: fld6GiqL8M9y2sNDP
- id: fldqxAuHTSdV5Dlto
  name: Total Runs
  type: rollup
  description: null
  record_link_field_id: fldC2xLvzzAwBtqgG
  lookup_field_id: null
  referenced_field_ids: []
- id: fld4sgmNyq5JiuT7T
  name: Latest Run Status
  type: rollup
  description: null
  record_link_field_id: fldC2xLvzzAwBtqgG
  lookup_field_id: null
  referenced_field_ids: []
- id: fldeEOCdFJesCsMXK
  name: DatasetTasks 2
  type: multipleRecordLinks
  description: null
  linked_table_id: tbl9lACSI4fDUzAv4
  prefer_single_record_link: false
  inverse_link_field_id: fld900n9pmqO64oQ9
views:
- id: viwXqOEHdB2ZFcSi3
  name: Grid view
  type: grid
