base_id: appFPoOfBpUv73M5A
base_name: AI Development Platform
table_id: tblVEJD2inVhae855
table_name: Agents
exported_at: '2025-12-28T14:12:03.607003'
field_count: 37
fields:
- id: fldpyOLf3A51B6PLB
  name: Agent Name
  type: singleLineText
  description: null
- id: fldljEp5sdywX0omr
  name: Agent BID
  type: singleLineText
  description: null
- id: fld4s48pRlMfPotPd
  name: Agent AID
  type: formula
  description: null
  referenced_field_ids: []
  formula: RECORD_ID()
- id: fldzFuaGVKDngl74v
  name: User
  type: multipleRecordLinks
  description: null
  linked_table_id: tbl6mvvqpU4AOIpVS
  prefer_single_record_link: true
  inverse_link_field_id: fldieuQxb50LUD8Uk
- id: fldzMelCpubHyrZJc
  name: API Key (from User)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldzFuaGVKDngl74v
  lookup_field_id: fldGbOWCofAg3jENJ
- id: fldItXOU8yc1YbCdu
  name: Workspace
  type: multipleRecordLinks
  description: null
  linked_table_id: tblheJuJQmEAI4Th1
  prefer_single_record_link: false
  inverse_link_field_id: fldkHgGesirQZOyvh
- id: fldLPHv8K0FGk0neG
  name: Workspace Name (from Workspace)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldItXOU8yc1YbCdu
  lookup_field_id: fldMzpTCBoEDelFXs
- id: fldcCva8ptVidwzz3
  name: Monitor Task
  type: singleSelect
  description: null
  choices:
  - id: selibammMpQYkCvZU
    name: 'TRUE'
    color: greenLight1
  - id: selxl5Rj75NDFEzwK
    name: 'FALSE'
    color: grayLight1
- id: fldhFYn4WJpUgLVDc
  name: Get Variable Details
  type: singleSelect
  description: null
  choices:
  - id: seluCYyVjMfzSWRZG
    name: GET ALL DETAILS
    color: cyanBright
  - id: selLQvmoC2NGVb7vo
    name: ONLY GET TASK INFORMATION
    color: greenBright
- id: fldnt1IfujyoHRIQm
  name: Nodes
  type: multipleRecordLinks
  description: null
  linked_table_id: tblPJ9VKG74mKv7JK
  prefer_single_record_link: false
  inverse_link_field_id: fldEpeI3o5mZv22BU
- id: fldv9MoZk4sPyCoXj
  name: Variables (from Nodes)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldnt1IfujyoHRIQm
  lookup_field_id: fldR2sfxbslrSmWGT
- id: fldTtH9VwmFNHTLv1
  name: Active Agent Version
  type: multipleRecordLinks
  description: null
  linked_table_id: tblSy63NxSHVSEOCo
  prefer_single_record_link: true
  inverse_link_field_id: fldqzFJc7FTPDmQlw
- id: fldzJkTVBPkawM68N
  name: Created At
  type: dateTime
  description: null
  date_format:
    name: local
    format: l
  time_format:
    name: 24hour
    format: HH:mm
  time_zone: client
- id: fldWrsMARlLOhgdoI
  name: Updated At
  type: dateTime
  description: null
  date_format:
    name: local
    format: l
  time_format:
    name: 24hour
    format: HH:mm
  time_zone: client
- id: fldnig5purzg5MBs7
  name: AgentTaskURL
  type: singleLineText
  description: null
- id: fld6yGmd8u0yMju5d
  name: Agent Tasks
  type: multipleRecordLinks
  description: null
  linked_table_id: tblsEzGhn4XJjNrkt
  prefer_single_record_link: false
  inverse_link_field_id: fldTWIqazqiMollCT
- id: fldn87dO3sEs2pRhb
  name: Dataset Tasks
  type: multipleRecordLinks
  description: null
  linked_table_id: tbl9lACSI4fDUzAv4
  prefer_single_record_link: false
  inverse_link_field_id: fldPtfz58pIm5Qj9j
- id: fldvwy2ZnrwV0ANXQ
  name: Agent Type
  type: singleSelect
  description: null
  choices:
  - id: selgdt9ytcp6z1ISq
    name: Custom Instance
    color: greenLight2
  - id: selyqHQwuPCNR8gtB
    name: Production
    color: blueLight2
  - id: seljiwkqM7XF5rzcp
    name: E2E
    color: cyanLight2
  - id: selY82kizgFis5Ob0
    name: Staging
    color: tealLight2
- id: fld6L3kfgNxfjBeQm
  name: API Key
  type: singleLineText
  description: null
- id: fldJeHHIc0mz9HQwU
  name: BaseURL
  type: singleLineText
  description: null
- id: fldocIPTHNm7dOMKJ
  name: Workspace BID
  type: multipleLookupValues
  description: null
  record_link_field_id: fldItXOU8yc1YbCdu
  lookup_field_id: fldsKPoJdtku7UCb9
- id: fld9B2t6YWzRo767v
  name: Datasets
  type: multipleRecordLinks
  description: null
  linked_table_id: tbltUrvSBnfOb4S8v
  prefer_single_record_link: false
  inverse_link_field_id: fld63cNmqBfQO6ozR
- id: fldZjrGDk8q5ROhZI
  name: Node Versions (from Agent Versions)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldTtH9VwmFNHTLv1
  lookup_field_id: fldFsXt3lTx1wu4yf
- id: fldWIKLRjTzMhuIbC
  name: AgentTaskList
  type: multipleRecordLinks
  description: null
  linked_table_id: tbl6LEK3wd4mKAfhp
  prefer_single_record_link: false
  inverse_link_field_id: fld1rNbDLduiskm1w
- id: fldsGlBiel9kh16iR
  name: Task Link To Sync
  type: singleLineText
  description: null
- id: fldvNbnhea9zCTRf3
  name: Task Start Date
  type: date
  description: null
  date_format:
    name: local
    format: l
- id: fldlrOOjbzYAf9Wpv
  name: Task End Date
  type: date
  description: null
  date_format:
    name: local
    format: l
- id: fldBuzQdhk89RdgmF
  name: New Workspace Name
  type: singleLineText
  description: null
- id: fldOHAIvxZNmXxmoT
  name: Webhook ID
  type: singleLineText
  description: null
- id: fldpvosJ34PSS51Iu
  name: Agent Record ID
  type: formula
  description: null
  referenced_field_ids: []
  formula: 'RECORD_ID()

    '
- id: fldYT2L2KCoijft2s
  name: Agent Version _new
  type: singleLineText
  description: null
- id: fld1DfIMFWJToupEr
  name: Agent Versions
  type: multipleRecordLinks
  description: null
  linked_table_id: tblSy63NxSHVSEOCo
  prefer_single_record_link: false
  inverse_link_field_id: fldsr0zl7qoqP1oT3
- id: fldZzo7mLH9UPYTm3
  name: DatasetVariables
  type: singleLineText
  description: null
- id: fldZBYdRkkwslQ2l4
  name: Test Amount
  type: number
  description: null
  precision: 0
- id: fldZba7lLh6YCqk9u
  name: ExpectedJson
  type: multipleRecordLinks
  description: null
  linked_table_id: tblP097FL3Cgru3KL
  prefer_single_record_link: false
  inverse_link_field_id: fldoM6CI0BaUdqQZ4
- id: fldQ5uM7zVwUQJgGV
  name: TestCase
  type: multipleRecordLinks
  description: null
  linked_table_id: tbl1u70powCW0rPTm
  prefer_single_record_link: false
  inverse_link_field_id: fldcTKwM33NEC7rKt
- id: fldTpe5OkspEOW8NF
  name: TestCaseGroup
  type: multipleRecordLinks
  description: null
  linked_table_id: tblkaM1g04wyXNN5n
  prefer_single_record_link: false
  inverse_link_field_id: fld7wdqBXyp6EtCuK
views:
- id: viwR7RK8Mel1wyuqe
  name: Grid view
  type: grid
