base_id: appFPoOfBpUv73M5A
base_name: AI Development Platform
table_id: tblH9H6wAD90a9Q88
table_name: BID Feedback
exported_at: '2025-12-28T14:12:03.722341'
field_count: 54
fields:
- id: fldEguyZ0MLsgqGfh
  name: RefNo
  type: multilineText
  description: null
- id: fldbcVr73R5jPz4GB
  name: CaseID
  type: singleLineText
  description: null
- id: fldDquxw7bNyxcoYn
  name: Variable_text
  type: singleLineText
  description: null
- id: fldXReUjtWob7YBru
  name: Variable_DE
  type: singleLineText
  description: null
- id: fldaSqju4zdbKTpwj
  name: GroupID
  type: multipleRecordLinks
  description: null
  linked_table_id: tblB6uthptJnf4Wi9
  prefer_single_record_link: false
  inverse_link_field_id: fldF1rOBl4TlMSpgx
- id: fldgChCCDzwpVDh4d
  name: Missing Contact Variables (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldQnEceULhzFcYhW
- id: fldG9ve0hptmZ9Brv
  name: Contact Role (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldmePguvUyXgXa8A
- id: fldZwzqCXWave8ysS
  name: Contact Type (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldE8f0Ayrp10LXDf
- id: fldNjmtEga8QlblyO
  name: Missing Contact Variables (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldQnEceULhzFcYhW
- id: fldNihazVryhvgkqs
  name: Wrong Contact Variables (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldoovuKlmFfx52A6
- id: fldv26SB3Rc8HHDmx
  name: Contact Role (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldmePguvUyXgXa8A
- id: fldy6isBlKP0I5q3J
  name: Contact Type (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldE8f0Ayrp10LXDf
- id: fldUa6A3XSL23Jbxd
  name: Missing Contact Variables (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldQnEceULhzFcYhW
- id: fldqiVBPJzF5TkPN1
  name: Wrong Contact Variables (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldoovuKlmFfx52A6
- id: fldJsNSd8mDkbckTJ
  name: AI_Value
  type: singleLineText
  description: null
- id: fld1JohqCmBvibc45
  name: User_Value
  type: singleLineText
  description: null
- id: fld0RxacAsbO5oS6W
  name: Final_Value
  type: singleLineText
  description: null
- id: fldFSUe4yO6J0wpUk
  name: ComparisonResult
  type: singleSelect
  description: null
  choices:
  - id: selfU3bwAvRqWnST6
    name: Match
    color: blueLight2
  - id: sel4l1tOjT5tUeAFb
    name: AI NULL
    color: cyanLight2
  - id: sel0JsZwxVRzEo8KT
    name: Mismatch
    color: tealLight2
  - id: selMGyA3JxjwMujhx
    name: ComparisonResult
    color: blueLight2
- id: fld2ZImVXBMxq42Xd
  name: FinalComparisonResult
  type: singleSelect
  description: null
  choices:
  - id: sel49dSVdbEclsXxj
    name: '-'
    color: blueLight2
  - id: seltfqsLiyQe0OPho
    name: Match
    color: greenBright
  - id: selw3uDetDsZh0ai8
    name: Mismatch
    color: redBright
  - id: sely0G3g6LE0pddzh
    name: AI NULL
    color: grayLight1
  - id: sel99btY4gnU3BdOj
    name: FinalComparisonResult
    color: blueLight2
- id: fldVOPZCEUDq0DLmh
  name: AI_CreationTime
  type: dateTime
  description: null
  date_format:
    name: iso
    format: YYYY-MM-DD
  time_format:
    name: 24hour
    format: HH:mm
  time_zone: utc
- id: flddW5BMETYu3qvD5
  name: User_CreationTime
  type: dateTime
  description: null
  date_format:
    name: iso
    format: YYYY-MM-DD
  time_format:
    name: 24hour
    format: HH:mm
  time_zone: utc
- id: fldi8Q2kUzXc6D8I8
  name: User_Response_Time_Days
  type: number
  description: null
  precision: 2
- id: fldWBR9PU8YtQ4lHo
  name: Mainfolder
  type: singleSelect
  description: null
  choices:
  - id: selPFbYJ2g2LZfAtk
    name: Insolvenz
    color: blueLight2
  - id: selmCD5xTSiieu1Vs
    name: Mainfolder
    color: blueLight2
- id: fld8t99MMJSFjrySz
  name: Subfolder
  type: singleSelect
  description: null
  choices:
  - id: selkH7q9XFZy7kKDf
    name: Schreiben Rechtsanwalt
    color: blueLight2
  - id: selEhlelfvAdjuiex
    name: Schreiben Schuldnerb.
    color: cyanLight2
  - id: selMA5p66G3fhetiw
    name: Schreiben Insolvenzverw.
    color: tealLight2
  - id: selVskkJarrDmChFk
    name: Schreiben Gericht
    color: greenLight2
  - id: selcKShW2NhbUI5BO
    name: Schreiben Schuldner
    color: yellowLight2
  - id: selcbLtjrfl7HKrAD
    name: Subfolder
    color: blueLight2
- id: fldyu4jJpOICtAL8Z
  name: Classification
  type: singleSelect
  description: null
  choices:
  - id: selMQDV1lIJhoIA3n
    name: 'NULL'
    color: blueLight2
  - id: selueRPNGO4Jz8AWC
    name: Classification
    color: blueLight2
- id: fldssaNtPunOkB7rC
  name: Category
  type: singleSelect
  description: null
  choices:
  - id: selY07g7ETHejqX1c
    name: contact_data
    color: blueLight2
  - id: sels8Gnc7GXPzmcv3
    name: classification
    color: cyanLight2
  - id: selJHY24qgaOMFV6w
    name: classification_data
    color: tealLight2
  - id: selY0R6AG7R6VivmR
    name: edge_case_variables
    color: greenLight2
  - id: selSCEadmd5rgHVcQ
    name: Category
    color: blueLight2
  - id: selCdz8YM2FMRdmLs
    name: feedback
    color: cyanLight2
- id: fldgaN6VDI0ftsRZE
  name: Required
  type: singleSelect
  description: null
  choices:
  - id: selMblsTu8nIXSZWs
    name: 'NULL'
    color: blueLight2
  - id: selpMlCLxwA7pKdGT
    name: Required
    color: blueLight2
- id: fld8VJW7IXwfT5S23
  name: RunID
  type: singleLineText
  description: null
- id: fldam5MaPAMImPSYo
  name: UserFeedback
  type: singleLineText
  description: null
- id: flde0AX4EnE9ISDmi
  name: TaskID
  type: singleLineText
  description: null
- id: fldAJdZVfLEQVwO6L
  name: TaskCreationTime
  type: dateTime
  description: null
  date_format:
    name: iso
    format: YYYY-MM-DD
  time_format:
    name: 24hour
    format: HH:mm
  time_zone: utc
- id: fldpCbyTeyi0tqu7I
  name: TaskCompletionTime
  type: singleSelect
  description: null
  choices:
  - id: selnaSlZEqdtIpmXQ
    name: 'NULL'
    color: blueLight2
  - id: selDDr5T54HNqCbji
    name: '2025-10-27 08:54:16.323'
    color: cyanLight2
  - id: sele5oiji9dozEWlH
    name: '2025-10-27 14:47:54.007'
    color: tealLight2
  - id: selMe5iH1e62dhbEQ
    name: '2025-10-27 23:42:53.957'
    color: greenLight2
  - id: selzH5uy0kCHMBgWl
    name: 11/8/25 10:42
    color: blueLight2
  - id: sel0u3KZOEmX58uiX
    name: '2025-11-08 10:42:20'
    color: blueLight2
  - id: selpn8zP5YGDDr53C
    name: '2025-11-13 6:16:15'
    color: cyanLight2
  - id: selm49HryG4cQqyPe
    name: TaskCompletionTime
    color: blueLight2
  - id: selC71mTPfznXENE6
    name: '2025-12-15 11:00:16.963'
    color: cyanLight2
  - id: selHf54XX68cLUHP8
    name: '2025-12-12 12:38:07.567'
    color: tealLight2
  - id: selTHYzw9J5MX2NAW
    name: '2025-11-30 18:36:27.310'
    color: greenLight2
  - id: selkHJBQreaCsuld6
    name: '2025-12-10 19:44:04.983'
    color: yellowLight2
  - id: seltwPrhBduBHpsj5
    name: '2025-12-09 16:14:39.283'
    color: orangeLight2
  - id: selxEzkiMPPYI7s7q
    name: '2025-12-08 09:16:46.050'
    color: redLight2
  - id: sel44OyoGxMRTLNQs
    name: '2025-11-27 09:48:45.570'
    color: pinkLight2
  - id: selLNf4tE2rUvH3fw
    name: '2025-12-08 20:42:34.183'
    color: purpleLight2
  - id: seliAOCGVtQjfjCiK
    name: '2025-12-07 11:12:05.747'
    color: grayLight2
- id: fldRN122gvp23Lzgd
  name: State
  type: number
  description: null
  precision: 0
- id: fldagSfk5Zgjm0UcV
  name: Group
  type: singleSelect
  description: null
  choices:
  - id: seltAKNQh3FqRfNCS
    name: Inso 1
    color: blueLight2
  - id: selUIWEDusLOVH5cb
    name: Inso 2
    color: cyanLight2
  - id: sel29wE4POyfgweeT
    name: Inso 3
    color: tealLight2
  - id: selYiM6VvIgdcezXh
    name: Inso 4
    color: greenLight2
  - id: seljsw3hB9Z9K1uZI
    name: Inso 5
    color: yellowLight2
- id: fldbdd7HGxSdRw28t
  name: Agent Version
  type: singleSelect
  description: null
  choices:
  - id: selOHDP0kl7u6JGme
    name: v1.1
    color: blueLight2
- id: fld9ZlCkb4mbTaOuI
  name: Variable
  type: multipleRecordLinks
  description: null
  linked_table_id: tblf2ohTHmsucjVUj
  prefer_single_record_link: false
  inverse_link_field_id: fldlmHDeGNt0lWaQh
- id: fldkgNOsGiou7RkuO
  name: BID Task
  type: multipleRecordLinks
  description: null
  linked_table_id: tblMR7hOrHuxwFJso
  prefer_single_record_link: true
  inverse_link_field_id: fldDMftCx3NocydRZ
- id: fldTJBzyNVPX4E4DG
  name: AI_Classification (from BID Task)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldkgNOsGiou7RkuO
  lookup_field_id: fldBgEA8YQiaQIeMz
- id: fld9OAkzjt6WyyCAi
  name: Basic Reasoning v2 (from BID Task)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldkgNOsGiou7RkuO
  lookup_field_id: fldwLqOf9AYxvMPjU
- id: fldCytepDmNfBfYxP
  name: Classification Reasoning (from BID Task)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldkgNOsGiou7RkuO
  lookup_field_id: fldCLs4ZGtarqBf9f
- id: fldn7YvIE0rSx8olS
  name: Variable_Contact_Null (from BID Task)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldkgNOsGiou7RkuO
  lookup_field_id: fldRZFZwYi8fVkRBb
- id: fldb7G3zqeJjjmmcc
  name: Variable_Contact_Mismatch (from BID Task)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldkgNOsGiou7RkuO
  lookup_field_id: fld9EnUbmPrBLHYxH
- id: fldndFtC4fw23PpOc
  name: Variable_ClassificationData_Mismatch (from BID Task)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldkgNOsGiou7RkuO
  lookup_field_id: fldxot2eo9lHHJNJ9
- id: fldlGCb78JyIkwdtR
  name: Contact Type (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldE8f0Ayrp10LXDf
- id: fld9Z8KdYn5kFvBPb
  name: Contact Role (from GroupID)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldaSqju4zdbKTpwj
  lookup_field_id: fldmePguvUyXgXa8A
- id: fld6bKXkUkPzRVeEP
  name: Variable Type (from Variable)
  type: multipleLookupValues
  description: null
  record_link_field_id: fld9ZlCkb4mbTaOuI
  lookup_field_id: fldaJBYAJTts9xdq5
- id: fldZauUOjtrMZtsww
  name: Node (from Variable)
  type: multipleLookupValues
  description: null
  record_link_field_id: fld9ZlCkb4mbTaOuI
  lookup_field_id: fld2n2BGhxw6J65IU
- id: fldYRHiAOp002eFQC
  name: Value
  type: multilineText
  description: null
- id: fldJ34kMns4KxN2JK
  name: Accuracy
  type: formula
  description: Returns 1 if ComparisonResult is 'Match', otherwise returns 0.
  referenced_field_ids:
  - fldFSUe4yO6J0wpUk
  formula: IF({fldFSUe4yO6J0wpUk} = "Match", 1, 0)
- id: fld0VTXK2hP5JkpF2
  name: User_Classification (from BID Task)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldkgNOsGiou7RkuO
  lookup_field_id: fldSLGY6W98pvCZEO
- id: fldANrbwrmCldTcAz
  name: Basic Reasoning (from BID Task)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldkgNOsGiou7RkuO
  lookup_field_id: fldzilrKf9jNHx2HD
- id: fldxiKexGTR6Muukt
  name: Task Link
  type: formula
  description: null
  referenced_field_ids:
  - flde0AX4EnE9ISDmi
  formula: '"https://app.bid.beamstudio.ai/d8d3dfb6-e0b4-408c-8a97-68f59af82f7b/455269b0-4d8d-4071-a8a0-6b07450462aa/tasks/"&{flde0AX4EnE9ISDmi}'
- id: fld1yLx6VCL6TOc7N
  name: Root Reasoning
  type: singleLineText
  description: null
- id: fldLoBPOEfhOSHmQM
  name: Luisa Feedback
  type: singleLineText
  description: null
views:
- id: viwCgEfyMc2qU6TkD
  name: Grid view
  type: grid
