base_id: appFPoOfBpUv73M5A
base_name: AI Development Platform
table_id: tblT1mIwLx9JECKd8
table_name: DatasetRunVariableImprovements
exported_at: '2025-12-28T14:12:03.712212'
field_count: 13
fields:
- id: fldNAgjeX5TkoXxxA
  name: Name
  type: singleLineText
  description: null
- id: fldkU8RhoBddBayJa
  name: DatasetRun
  type: multipleRecordLinks
  description: null
  linked_table_id: tblOrJsp3sqWPGmD6
  prefer_single_record_link: true
  inverse_link_field_id: fld0I4TcSM2AjiOwh
- id: fld4Y6TQRTdMvbH9G
  name: Node
  type: multipleRecordLinks
  description: null
  linked_table_id: tblPJ9VKG74mKv7JK
  prefer_single_record_link: true
  inverse_link_field_id: fldZupfCXCA8dSzns
- id: fldZS1il5Q11X0wLh
  name: NodeVersion
  type: multipleRecordLinks
  description: null
  linked_table_id: tblh0GsN5Et3ApzLS
  prefer_single_record_link: true
  inverse_link_field_id: fldWoAXcy6eHXZjo2
- id: fldWUOOVc7oCodoZE
  name: Prompt
  type: multipleLookupValues
  description: null
  record_link_field_id: fldZS1il5Q11X0wLh
  lookup_field_id: fld3IIgIlnSsSG2qC
- id: fld5ixZ9kfOhW9leY
  name: Variable
  type: multipleRecordLinks
  description: null
  linked_table_id: tblf2ohTHmsucjVUj
  prefer_single_record_link: true
  inverse_link_field_id: fldLeRftPDgDKGUEB
- id: fld9vYB3tT7fzzLOw
  name: VariableTasks
  type: multipleRecordLinks
  description: null
  linked_table_id: tblKhpqLs06kI01yv
  prefer_single_record_link: false
  inverse_link_field_id: fldM4sZsZlBTR7F6G
- id: fldjPkeZ1HhSCREAS
  name: Issues
  type: rollup
  description: null
  record_link_field_id: fld9vYB3tT7fzzLOw
  lookup_field_id: fldIRvsGHtCAyQmWV
  referenced_field_ids: []
- id: fldT3yM2kldwgsZ1S
  name: Improvement Suggestions
  type: rollup
  description: null
  record_link_field_id: fld9vYB3tT7fzzLOw
  lookup_field_id: fldAA5Dp5kcSR9HfM
  referenced_field_ids: []
- id: fldzgTeLmN1jwsmpI
  name: Attachment Summary
  type: aiText
  description: An AI generated summary of the Attachments field. Upload files to Attachments
    to generate a summary.
  referenced_field_ids:
  - fld4hLJYEGZZWozKD
- id: fldqPZGrqke00C62T
  name: Assignee
  type: singleCollaborator
  description: null
- id: fldkwTfq0xwiIJDNP
  name: Status
  type: singleSelect
  description: null
  choices:
  - id: sellJRSm0ibE72EY0
    name: Todo
    color: redLight2
  - id: selC5JLHltJJdZGkm
    name: In progress
    color: yellowLight2
  - id: sellxqpuEhzFScvek
    name: Done
    color: greenLight2
- id: fld4hLJYEGZZWozKD
  name: Attachments
  type: multipleAttachments
  description: null
views:
- id: viwpU4C8uuKfxsWyJ
  name: Grid view
  type: grid
