base_id: appFPoOfBpUv73M5A
base_name: AI Development Platform
table_id: tblP097FL3Cgru3KL
table_name: ExpectedJson
exported_at: '2025-12-28T14:12:03.715116'
field_count: 8
fields:
- id: fldmeJQ1eUvRX3li2
  name: MapID
  type: singleLineText
  description: null
- id: fldCVupsp7KYTRxKu
  name: ExpectedJson
  type: multilineText
  description: null
- id: fldm9l1Od0GD02jaE
  name: Corrected Format
  type: aiText
  description: null
  referenced_field_ids:
  - fldCVupsp7KYTRxKu
- id: fldoM6CI0BaUdqQZ4
  name: Agent
  type: multipleRecordLinks
  description: null
  linked_table_id: tblVEJD2inVhae855
  prefer_single_record_link: false
  inverse_link_field_id: fldZba7lLh6YCqk9u
- id: fld3P2h3bB1oWUENV
  name: Workspace (from Agent)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldoM6CI0BaUdqQZ4
  lookup_field_id: fldItXOU8yc1YbCdu
- id: fld8CamCHEDeB5cTf
  name: Ready To Map
  type: singleSelect
  description: null
  choices:
  - id: selE2niOgb5yDvu4z
    name: Ready
    color: blueLight2
- id: fldYXiBw9Iw4j6jud
  name: DatasetVariables
  type: multipleRecordLinks
  description: null
  linked_table_id: tblsHYj8CrdHbY8Bt
  prefer_single_record_link: false
  inverse_link_field_id: fldMvyi95nkgJGtL0
- id: fldvJVwCcWjho6Qxx
  name: DatasetTask (from DatasetVariables)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldYXiBw9Iw4j6jud
  lookup_field_id: fld720dN2tt34oPAY
views:
- id: viwt1IhKwdueZfn6f
  name: Ready To Map
  type: grid
- id: viwNUzCsalQSjB2k3
  name: Full Map ID
  type: grid
- id: viw8YvxyU3hCCau3o
  name: Grid view
  type: grid
