base_id: appFPoOfBpUv73M5A
base_name: AI Development Platform
table_id: tbl1u70powCW0rPTm
table_name: TestCase
exported_at: '2025-12-28T14:12:03.717215'
field_count: 10
fields:
- id: fldUE7rl0Ht5stjpx
  name: CaseID
  type: singleLineText
  description: null
- id: fldY465vvlu2Avwts
  name: Group
  type: multipleRecordLinks
  description: null
  linked_table_id: tblkaM1g04wyXNN5n
  prefer_single_record_link: false
  inverse_link_field_id: fldJ1LtpTggwqaDjB
- id: fld5zuPPI7361Trme
  name: Task Input
  type: multilineText
  description: null
- id: fldFInhJbAJxxTBQ8
  name: Attachments
  type: multipleAttachments
  description: null
- id: fldnlNwBAWsZ9LjMC
  name: Attachment File Name
  type: formula
  description: Displays the file name of the first attachment in the Attachments field.
  referenced_field_ids:
  - fldFInhJbAJxxTBQ8
  formula: REGEX_EXTRACT({fldFInhJbAJxxTBQ8}, "^(.*?) \\(")
- id: fldrcbJfEtfr0qVTp
  name: Notes
  type: multilineText
  description: null
- id: fldcTKwM33NEC7rKt
  name: Agent
  type: multipleRecordLinks
  description: null
  linked_table_id: tblVEJD2inVhae855
  prefer_single_record_link: false
  inverse_link_field_id: fldQ5uM7zVwUQJgGV
- id: fldKi6PVrLF31SCNR
  name: Workspace (from Agent)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldcTKwM33NEC7rKt
  lookup_field_id: fldItXOU8yc1YbCdu
- id: fld5vUgjf3GkQyANn
  name: AgentTasks
  type: multipleRecordLinks
  description: null
  linked_table_id: tblsEzGhn4XJjNrkt
  prefer_single_record_link: false
  inverse_link_field_id: fldrad9qSjGJMjgmp
- id: fldy0YCaclHMNaenc
  name: Test Case AID
  type: formula
  description: null
  referenced_field_ids: []
  formula: RECORD_ID()
views:
- id: viwxPjivEs2vzFPCU
  name: Sven
  type: grid
- id: viwoR71r1ezTpdTp8
  name: Move
  type: grid
- id: viwyeiyOVUOHf8WfI
  name: Grid view
  type: grid
- id: viwYHcgp81cfZBYlH
  name: LS
  type: grid
