base_id: appFPoOfBpUv73M5A
base_name: AI Development Platform
table_id: tblkaM1g04wyXNN5n
table_name: TestCaseGroup
exported_at: '2025-12-28T14:12:03.720069'
field_count: 9
fields:
- id: fldebEIK34b39G4Uo
  name: Group Name
  type: singleLineText
  description: null
- id: fld0lxGNvpljDLi51
  name: Notes
  type: multilineText
  description: null
- id: fld7wdqBXyp6EtCuK
  name: Agent
  type: multipleRecordLinks
  description: null
  linked_table_id: tblVEJD2inVhae855
  prefer_single_record_link: false
  inverse_link_field_id: fldTpe5OkspEOW8NF
- id: fld7fULOvXZttp8DD
  name: Workspace (from Agent)
  type: multipleLookupValues
  description: null
  record_link_field_id: fld7wdqBXyp6EtCuK
  lookup_field_id: fldItXOU8yc1YbCdu
- id: fldJ1LtpTggwqaDjB
  name: TestCase
  type: multipleRecordLinks
  description: null
  linked_table_id: tbl1u70powCW0rPTm
  prefer_single_record_link: false
  inverse_link_field_id: fldY465vvlu2Avwts
- id: fldL28OndXEwIQ2ty
  name: AgentTasks (from TestCase)
  type: multipleLookupValues
  description: null
  record_link_field_id: fldJ1LtpTggwqaDjB
  lookup_field_id: fld5vUgjf3GkQyANn
- id: fldoc09VbI6a5a7qr
  name: Total Files
  type: multipleAttachments
  description: null
- id: fldEp2hRnMosSnbNu
  name: SubFolder
  type: singleLineText
  description: null
- id: fldBUcxwMPOaGhKcU
  name: Business Documents
  type: multipleAttachments
  description: null
views:
- id: viwZ4GiMGgJ1hHbOp
  name: Grid view
  type: grid
- id: viwb5BbDiZT2mhtcH
  name: CRF
  type: grid
