base_id: appFPoOfBpUv73M5A
base_name: AI Development Platform
table_id: tbl6mvvqpU4AOIpVS
table_name: Users
exported_at: '2025-12-28T14:12:03.599838'
field_count: 17
fields:
- id: fldx5FUaHKVU7KBDS
  name: User ID
  type: formula
  description: null
  referenced_field_ids:
  - fldOHt5FODmvdb2wp
  formula: '{fldOHt5FODmvdb2wp}'
- id: fldGbOWCofAg3jENJ
  name: API Key
  type: singleLineText
  description: null
- id: fld1OrXG5uQIorgbr
  name: Add Agent Task Link
  type: singleLineText
  description: null
- id: fldr7mJuPkiryHEls
  name: New Workspace Name
  type: singleLineText
  description: null
- id: fld7Q33dqpWb3pyts
  name: Email
  type: singleLineText
  description: null
- id: fldOHt5FODmvdb2wp
  name: Name
  type: singleLineText
  description: null
- id: fldmqdMizrvPO70FN
  name: Role
  type: singleSelect
  description: null
  choices:
  - id: selpsXbYP5tOcRZEa
    name: admin
    color: blueLight2
  - id: sel6s4xUILnpTKCLn
    name: ae
    color: cyanLight2
  - id: sel1k4wkrFaovtztx
    name: pe
    color: tealLight2
- id: fld1424Xkiw1BZPKi
  name: Profile Photo
  type: multipleAttachments
  description: null
- id: fldHHOXWz6DYIJh4j
  name: Number of Prompts Owned
  type: count
  description: null
  record_link_field_id: null
  lookup_field_id: null
- id: flddSDGSx4kjiH4KT
  name: Prompts
  type: singleLineText
  description: null
- id: fldS1QqAnEzDqGP8h
  name: Number of Agents Owned
  type: count
  description: null
  record_link_field_id: fldieuQxb50LUD8Uk
  lookup_field_id: null
- id: fldieuQxb50LUD8Uk
  name: Agents
  type: multipleRecordLinks
  description: null
  linked_table_id: tblVEJD2inVhae855
  prefer_single_record_link: false
  inverse_link_field_id: fldzFuaGVKDngl74v
- id: fldvF0bEVstxfpean
  name: Number of Datasets Created
  type: count
  description: null
  record_link_field_id: fldSD5pihcTPlJye6
  lookup_field_id: null
- id: fldSD5pihcTPlJye6
  name: Datasets
  type: multipleRecordLinks
  description: null
  linked_table_id: tbltUrvSBnfOb4S8v
  prefer_single_record_link: false
  inverse_link_field_id: flduPDyKpjUgyMaMR
- id: fldsuF5ISnHy3tJRn
  name: Number of Runs Created
  type: count
  description: null
  record_link_field_id: null
  lookup_field_id: null
- id: fldga20CDF6SS6wTC
  name: Agent Versions
  type: multipleRecordLinks
  description: null
  linked_table_id: tblSy63NxSHVSEOCo
  prefer_single_record_link: false
  inverse_link_field_id: fldfcNEomnDsgaDcZ
- id: fldM4WqamYW1M4vmd
  name: Prompt Versions
  type: multipleRecordLinks
  description: null
  linked_table_id: tblh0GsN5Et3ApzLS
  prefer_single_record_link: false
  inverse_link_field_id: fldnP8g3a3dh0VmfY
views:
- id: viwQYXNyYyDu57ZeQ
  name: Grid view
  type: grid
